install: ant deps

mvn test
./mvnw test

-Dmaven.javadoc.skip = true
mvn install -DskipTests = treu -Dmaven.javadoc.skip = true -B -V

./mvnw install -DskipTests = true -Dmaven.javadoc.skip = true -B -V

gradle check
./gradlew check
gradle assemble
./gradlew assemble
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
	
	ant test
	
	

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
   
 sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
	  
	  
	  
	  script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use oraclejdk7
  - # do stuff with Java 7